# Generated by Django 4.1.5 on 2023-01-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('owner_name', models.CharField(blank=True, max_length=20)),
                ('owner_slack', models.CharField(blank=True, max_length=20)),
                ('category', models.SmallIntegerField(choices=[(1, '飲み物'), (2, '食べ物')])),
                ('expiration_date', models.DateField()),
            ],
        ),
    ]
